### PR TITLE
Adding Gradle wrapper file to the repo

### PR DESCRIPTION
**Pull request by vrajeshkanna**
#21 
.jar is ignored in .gitignore. Added an exception for gradle-wrapper.jar and pushed the .jar file also.

### CODE REVIEW

**Comment by vrajeshkanna** [comment]
#23 
Removed resources folder from .gitignore and added resource folder to make the build successful

**Comment by vrajeshkanna** [comment]
Closed PR by mistake. It is not merged yet

**Comment by natterstefan** [comment]
Hi @xotahal, I just stumbled upon https://github.com/xotahal/react-native-material-ui and tried to install the demo. Got caught up in this issue. Do you know when you have time to merge/test it? Thanks for your time and work.

**Comment by DaniGuardiola** [comment]
Tested this PR @vrajeshkanna, it fixes this issue https://github.com/xotahal/react-native-material-ui-demo-app/issues/21

**Review by xotahal — APPROVED** [review]

**Pull request merged**
